### ISSUE TITLE
Admin login form is broken

### ISSUE THREAD

**Issue by igloox** [harmo/django-email-as-username#5]
On Django 1.8, trying to log in using the admin login form fails. `EmailAdminAuthenticationForm.clean()` tries to call `self.check_for_test_cookie()`, which raises an error::

```
AttributeError: 'EmailAdminAuthenticationForm' object has no attribute 'check_for_test_cookie'
```

The `EmailAuthenticationForm.clean()` method checks if the method exists using `hasattr` before attempting to call it - I presume the EmailAdminAuthenticationForm should do the same?

**Comment by harmo** [comment]
@igloox  Thanks for the bug report, it will be ok on the next pypi version.
