### ISSUE TITLE
Exception using with Django 1.8.6: django.core.exceptions.ImproperlyConfigured

### ISSUE THREAD

**Issue by matheuscas** [harmo/django-email-as-username#6]
When I try to run my application, the following error appears: 

django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form EmailUserChangeForm needs updating.

**Comment by harmo** [comment]
Thanks for the report @matheuscas  !

I've just ran a fresh install on a 1.8.6 django and I don't have this error. Also, in this form the _field_ attribute is given for django > 1.7 ([see here](https://github.com/harmo/django-email-as-username/blob/master/emailusernames/forms.py#L124-L125))

No override of this form in your app ? 
Can you test if the VERSION var is correct in your app ? `from django import VERSION`

**Comment by matheuscas** [comment]
I actually checked the version using `from django import VERSION` See: `(1, 8, 6, 'final', 0)`. But I'm not using any forms directly. I'm using in my API (with Tastypie) to create and check users using email. The only form possible is the UserProfile (a class to extend user model) added to admin site, otherwise nothing else. I'm investigation other possibilities, but for now, no success. 
And yes, I digged around the source and I saw this version verification and that's why I opened the issue. :/

**Comment by harmo** [comment]
Ok thanks for this precisions.

I'll try to add some unit tests soon to recreate the error.

**Comment by matheuscas** [comment]
@harmo I think I've found the problem. Installing from pip I receive the following version: django-email-as-username (1.6.7). So far, nothing new. However, looking for the code in my virtualenv folder, the class **EmailUserChangeForm** is missing the VERSION verification. See how it is:

``` python
class EmailUserChangeForm(UserChangeForm):
    """
    Override the default UserChangeForm to force email-as-username behavior.
    """
    email = forms.EmailField(label=_("Email"), max_length=75)

    class Meta:
        model = User

    def __init__(self, *args, **kwargs):
        super(EmailUserChangeForm, self).__init__(*args, **kwargs)
        del self.fields['username']
```

Hence, Django freaks and throws the exception.

**Comment by harmo** [comment]
Yep, this package is no longer updated, that's why I forked the repo. The new package is named 
**py2-py3-django-email-as-username**

https://pypi.python.org/pypi?:action=display&name=py2-py3-django-email-as-username&version=1.7.1

If it work fine you can close this ticket. And thanks again for the report !

**Comment by matheuscas** [comment]
I've installed from source and worked like a charm. Maybe you guys could update README. Thanks for the replies.
